### ISSUE TITLE
How can I use icojs in a Firefox browser extension

### ISSUE THREAD

**Issue by odebroqueville** [egy186/icojs#126]
Hi, I'd like to use your icon parser in my Firefox extension 'Context Search' to obtain an array of png images from an ico file. I'm new to JS dev and would be very grateful if you would help me integrate your code in the extension code to be able to use parse(buffer, [mime]) ⇒ Promise.<Array.<ParsedImage>>. You can find my extension here: https://github.com/odebroqueville/contextSearch (the latest version still has some bugs that I need to iron out!).

**Comment by odebroqueville** [comment]
Hi egy, I'm sorry if this is a stupid question, but where do I find dist/ico.js? Do I need to do a local npm install or something like that? I saw some 'require' commands in your code, but I think this only works with node.js and not in the browser. Also, I think I'll have to add ico.js to the background scripts rather than content scripts.

**Comment by egy186** [comment]
Hi, dist/ico.js is a bundled version of icojs and we can use `ICO.parse` as a parse function in the browser. dist/ico.js is included in the [npm package](https://www.npmjs.com/package/icojs) or please download from https://unpkg.com/icojs/.

Importing in the background scripts seems to be similar as content scripts way (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json).
In the manifest.json:
```json
"background": {
  "scripts": ["ico.js", "background.js"]
}
```
then in the background.js:
```js
ICO.parse(icon)
```

**Comment by odebroqueville** [comment]
Thanks egy, will let you know how it goes.

**Comment by egy186** [comment]
Hi, I created a firefox extension to use icojs in the background script and it seems to be working propely on Firefox v63.0.1. The repository is [here](https://github.com/egy186/icojs-in-webextension)!

**Comment by egy186** [comment]
You are right, only dist/ico.js is needed on the browser. dist/ico.js is bundled and minified by using [Rollup](https://rollupjs.org/) and the entry point is [here](https://github.com/egy186/icojs/blob/master/src/browser/index.js).

**Comment by egy186** [comment]
Closing inactive issue.
