### ISSUE TITLE
Improve for cursor files (.CUR)?

### ISSUE THREAD

**Issue by theviking** [egy186/icojs#14]
Any hints on how to revise for .CUR files? According to some sources these file types are very similar other than the hot spot definition in the cursor files.

**Comment by theviking** [comment]
Would you know how to extract the hot spot data?

**Comment by egy186** [comment]
Each parsed data has `hotspot` key:
```js
ICO.parseSync(fs.readFileSync('cursor.cur'))[0].hotspot // { x: Number, y: Number }
```
