### ISSUE TITLE
Unhandled rejection TypeError: this is not a typed array

### ISSUE THREAD

**Issue by kirrg001** [egy186/icojs#24]
Hey 😎

I am getting an unhandled error when uploading an `ico`.

```
Unhandled rejection TypeError: this is not a typed array.
    at Function.from (native)
    at Object.decode (/Users/kirrg001/dev/ghost/ghost/node_modules/icojs/src/image.js:15:29)
    at Image.decode.then (/Users/kirrg001/dev/ghost/ghost/node_modules/icojs/src/parse-ico.js:50:20)
    at /Users/kirrg001/dev/ghost/ghost/node_modules/icojs/src/parse-ico.js:59:14
```

This is how we use icojs
```
var arrayBuffer = new Uint8Array(fs.readFileSync(path)).buffer;
ICO.parse(arrayBuffer).then(....)
```

Here is the ico.
[soffice.zip](https://github.com/egy186/icojs/files/864311/soffice.zip)

Thank you so much for your work!

**Comment by egy186** [comment]
Thanks for the report.

The error seems to be related to `Buffer.from` ([this line](https://github.com/egy186/icojs/blob/v0.7.0/src/image.js#L15)) and the version of Node.js, according to [stackoverflow](https://stackoverflow.com/questions/36899888/getting-typeerror-this-is-not-a-typed-array-using-buffer-from-in-mocha).
Which version of Node.js you are using?

**Comment by kirrg001** [comment]
Hey!

v4.4.7. does not work
v6.9.0 works

Totally forgot to test other node versions.

**Comment by egy186** [comment]
Fixed in v0.7.1!

**Comment by kirrg001** [comment]
Thank you so much. Can confirm, works now 👍

**Comment by ashsihk11** [comment]
Perfect works now :+1:
