### ISSUE TITLE
Is there a way to make this synchronous?

### ISSUE THREAD

**Issue by theviking** [egy186/icojs#44]
I would like to use this in a script to run periodically. I would like to write the images synchronous and not use a promise as I would like to write the png file name into a json array.

Is there a way to do this?

**Comment by egy186** [comment]
We cannot parse synchronously in version 0.7.2. icojs uses jimp as image encoder/decoder and `Jimp.read` returns a promise.
Async/await in es2017 doesn't help you?

BTW each module (bmp-js, jpeg-js and pngjs) which jimp depends on seems to have a synchronous method. I try to use these methods directly.
